---
- name: Building application
  hosts:build
  become:yes

  tasks:
    -name:Ensure git is present
    apt:
      name: git
      state:present

  -name:Ensure java is present
  apt:
    name: defuult-jdk
    state:present