---
- name: Launching the application
  hosts:prod
  become:yes

  tasks:
    - name: Enshure git is present
    apt:
      name:git
      state:present

    - name: Ensure java is present
    apt:
      name: default-jdk
      state: present

    - name: